export const stadiumLocations = [
  {
    team: "Atlanta Hawks",
    arena: "State Farm Arena",
    city: "Atlanta, GA",
    coordinates: [33.7573, -84.3963],
  },
  {
    team: "Boston Celtics",
    arena: "TD Garden",
    city: "Boston, MA",
    coordinates: [42.3663, -71.0622],
  },
  {
    team: "Brooklyn Nets",
    arena: "Barclays Center",
    city: "Brooklyn, NY",
    coordinates: [40.6826, -73.9754],
  },
  {
    team: "Charlotte Hornets",
    arena: "Spectrum Center",
    city: "Charlotte, NC",
    coordinates: [35.2251, -80.8392],
  },
  {
    team: "Chicago Bulls",
    arena: "United Center",
    city: "Chicago, IL",
    coordinates: [41.8807, -87.6742],
  },
  {
    team: "Cleveland Cavaliers",
    arena: "Rocket Mortgage FieldHouse",
    city: "Cleveland, OH",
    coordinates: [41.4964, -81.6881],
  },
  {
    team: "Dallas Mavericks",
    arena: "American Airlines Center",
    city: "Dallas, TX",
    coordinates: [32.7906, -96.8103],
  },
  {
    team: "Denver Nuggets",
    arena: "Ball Arena",
    city: "Denver, CO",
    coordinates: [39.7486, -105.0075],
  },
  {
    team: "Detroit Pistons",
    arena: "Little Caesars Arena",
    city: "Detroit, MI",
    coordinates: [42.3410, -83.0550],
  },
  {
    team: "Golden State Warriors",
    arena: "Chase Center",
    city: "San Francisco, CA",
    coordinates: [37.7680, -122.3877],
  },
  {
    team: "Houston Rockets",
    arena: "Toyota Center",
    city: "Houston, TX",
    coordinates: [29.7508, -95.3622],
  },
  {
    team: "Indiana Pacers",
    arena: "Gainbridge Fieldhouse",
    city: "Indianapolis, IN",
    coordinates: [39.7639, -86.1556],
  },
  {
    team: "Los Angeles Clippers",
    arena: "Crypto.com Arena",
    city: "Los Angeles, CA",
    coordinates: [34.0431, -118.2676],
  },
  {
    team: "Los Angeles Lakers",
    arena: "Crypto.com Arena",
    city: "Los Angeles, CA",
    coordinates: [34.0431, -118.2676],
  },
  {
    team: "Memphis Grizzlies",
    arena: "FedExForum",
    city: "Memphis, TN",
    coordinates: [35.1382, -90.0506],
  },
  {
    team: "Miami Heat",
    arena: "Kaseya Center",
    city: "Miami, FL",
    coordinates: [25.7814, -80.1881],
  },
  {
    team: "Milwaukee Bucks",
    arena: "Fiserv Forum",
    city: "Milwaukee, WI",
    coordinates: [43.0451, -87.9173],
  },
  {
    team: "Minnesota Timberwolves",
    arena: "Target Center",
    city: "Minneapolis, MN",
    coordinates: [44.9795, -93.2761],
  },
  {
    team: "New Orleans Pelicans",
    arena: "Smoothie King Center",
    city: "New Orleans, LA",
    coordinates: [29.9490, -90.0821],
  },
  {
    team: "New York Knicks",
    arena: "Madison Square Garden",
    city: "New York, NY",
    coordinates: [40.7506, -73.9936],
  },
  {
    team: "Oklahoma City Thunder",
    arena: "Paycom Center",
    city: "Oklahoma City, OK",
    coordinates: [35.4634, -97.5150],
  },
  {
    team: "Orlando Magic",
    arena: "Amway Center",
    city: "Orlando, FL",
    coordinates: [28.5392, -81.3839],
  },
  {
    team: "Philadelphia 76ers",
    arena: "Wells Fargo Center",
    city: "Philadelphia, PA",
    coordinates: [39.9012, -75.1719],
  },
  {
    team: "Phoenix Suns",
    arena: "Footprint Center",
    city: "Phoenix, AZ",
    coordinates: [33.4458, -112.0714],
  },
  {
    team: "Portland Trail Blazers",
    arena: "Moda Center",
    city: "Portland, OR",
    coordinates: [45.5316, -122.6668],
  },
  {
    team: "Sacramento Kings",
    arena: "Golden 1 Center",
    city: "Sacramento, CA",
    coordinates: [38.5808, -121.4998],
  },
  {
    team: "San Antonio Spurs",
    arena: "Frost Bank Center",
    city: "San Antonio, TX",
    coordinates: [29.4269, -98.4375],
  },
  {
    team: "Toronto Raptors",
    arena: "Scotiabank Arena",
    city: "Toronto, ON",
    coordinates: [43.6435, -79.3791],
  },
  {
    team: "Utah Jazz",
    arena: "Delta Center",
    city: "Salt Lake City, UT",
    coordinates: [40.7683, -111.9011],
  },
  {
    team: "Washington Wizards",
    arena: "Capital One Arena",
    city: "Washington, D.C.",
    coordinates: [38.8981, -77.0209],
  },
];
